[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm dlx serve -s dist/public -l $PORT --no-cache"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
